server:
  port: 80

cors:
  originPatterns: http://localhost:8080,https://erudio.com.br,http://localhost:3000

file:
  upload-dir: /Users/Miguel/Downloads/UploadDir

security:
  jwt:
    token:
      secret-key: 53cr37
      expire-length: 3600000

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
#      ddl-auto: update // deixar habilitado ate o hibernate criar as tabelas e vc salvar ela no db.migration
       dll-auto: none
    jdbc:
      lob:
        non_contextual_creation: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
      show-sql: true

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB

springdoc:
  pathsToMatch:
    - /api/**/v1/**
    - /auth/**
  swagger-ui:
    use-root-path: true

flyway:
  url: jdbc:postgresql://localhost:5432/
  schemas: rest_with_spring_boot_erudio
  user: postgres
  password: 321987