spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rest_with_spring_boot_erudio?useTimeZone=true&serverTimeZone=UTC
    username: root
    password: 321987
  jpa:
    hibernate:
#      ddl-auto: update // deixar habilitado ate o hibernate criar as tabelas e vc salvar ela no db.migration
       dll-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
      show-sql: false
springdoc:
  pathsToMatch: /api/**/v1/**
  swagger-ui:
    use-root-path: true